-- Application-owned integration fixture; never applied by dbsetup.
INSERT INTO food_families (id, names) VALUES (1, '{"en":"Pizza","pl":"Pizza"}');

INSERT INTO food_objects
    (id, names, nutrition_basis, protein, carbohydrate, fat, serving, food_family_id, image_key)
VALUES
    (1,  '{"en": "Pizza Margherita",   "pl": "Pizza margherita"}'::jsonb,   'g',  10,   30,   10,   350,   1,    'pizza-margherita'),
    (2,  '{"en": "Pizza Capricciosa",  "pl": "Pizza capricciosa"}'::jsonb,  'g',  11,   28,   11,   350,   1,    NULL),
    (3,  '{"en": "Lasagna",            "pl": "Lazania"}'::jsonb,            'g',  9,    18,   8,    350,   NULL, NULL),
    (4,  '{"en": "Pierogi",            "pl": "Pierogi"}'::jsonb,            'g',  6,    32,   5,    250,   NULL, NULL),
    (5,  '{"en": "Chicken breast",     "pl": "Pierś z kurczaka"}'::jsonb,   'g',  31,   0,    3.6,  NULL,  NULL, 'chicken-breast'),
    (6,  '{"en": "Pork chop",          "pl": "Kotlet wieprzowy"}'::jsonb,   'g',  27,   0,    14,   NULL,  NULL, NULL),
    (7,  '{"en": "Beef steak",         "pl": "Stek wołowy"}'::jsonb,        'g',  26,   0,    15,   NULL,  NULL, NULL),
    (8,  '{"en": "Mixed berries",      "pl": "Owoce jagodowe"}'::jsonb,     'g',  1,    12,   0.5,  NULL,  NULL, NULL),
    (9,  '{"en": "Apple juice",        "pl": "Sok jabłkowy"}'::jsonb,       'ml', 0.1,  11,   0.1,  NULL,  NULL, NULL),
    (10, '{"en": "Milk",               "pl": "Mleko"}'::jsonb,              'ml', 3.4,  4.8,  2,    NULL,  NULL, 'milk'),
    (11, '{"en": "Skyr yogurt",        "pl": "Jogurt skyr"}'::jsonb,        'g',  11,   4,    0.2,  150,   NULL, NULL),
    (12, '{"en": "Greek yogurt",       "pl": "Jogurt grecki"}'::jsonb,      'g',  9,    4,    5,    170,   NULL, NULL),
    (13, '{"en": "Gyoza",              "pl": "Pierożki gyoza"}'::jsonb,     'g',  8,    24,   8,    200,   NULL, 'gyoza'),
    (14, '{"en": "Oat milk",           "pl": "Napój owsiany"}'::jsonb,      'ml', 1,    7,    1.5,  NULL,  NULL, NULL),
    (15, '{"en": "Kebab",              "pl": "Kebab"}'::jsonb,              'g',  15,   18,   12,   350,   NULL, NULL),
    (16, '{"en": "Gyros",              "pl": "Gyros"}'::jsonb,              'g',  18,   10,   14,   300,   NULL, NULL),
    (17, '{"en": "Polish chicken soup","pl": "Rosół"}'::jsonb,              'ml', 2,    1,    1,    300,   NULL, NULL),
    (18, '{"en": "Butter",             "pl": "Masło"}'::jsonb,              'g',  0.5,  0.5,  82,   NULL,  NULL, NULL),
    (19, '{"en": "Olive oil",          "pl": "Oliwa z oliwek"}'::jsonb,     'ml', 0,    0,    91.3, NULL,  NULL, NULL),
    (20, '{"en": "Protein shake",      "pl": "Shake białkowy"}'::jsonb,     'ml', 8,    4,    1,    300,   NULL, NULL),
    (21, '{"en": "Beef cheeseburger",  "pl": "Cheeseburger wołowy"}'::jsonb,'g',  13,   24,   13,   220,   NULL, NULL),
    (22, '{"en": "Fried chicken wings","pl": "Smażone skrzydełka z kurczaka"}'::jsonb, 'g', 22, 8, 20, 180, NULL, NULL),
    (23, '{"en": "Turkey breast",      "pl": "Pierś z indyka"}'::jsonb,      'g',  29,   0,    2,    NULL,  NULL, NULL),
    (24, '{"en": "Pickled cucumbers",  "pl": "Ogórki kiszone"}'::jsonb,     'g',  0.5,  2,    0.2,  NULL,  NULL, NULL),
    (25, '{"en": "Tomatoes",           "pl": "Pomidory"}'::jsonb,           'g',  0.9,  3.9,  0.2,  NULL,  NULL, NULL),
    (26, '{"en": "Pancakes",           "pl": "Naleśniki"}'::jsonb,          'g',  6,    28,   7,    150,   NULL, NULL),
    (27, '{"en": "Omelette",           "pl": "Omlet"}'::jsonb,              'g',  11,   1,    12,   180,   NULL, NULL),
    (28, '{"en": "Oatmeal",            "pl": "Owsianka"}'::jsonb,           'g',  2.5,  12,   1.5,  250,   NULL, NULL),
    (29, '{"en": "Paella",             "pl": "Paella"}'::jsonb,             'g',  8,    20,   5,    350,   NULL, NULL),
    (30, '{"en": "Pho",                "pl": "Zupa pho"}'::jsonb,           'ml', 3,    8,    1.5,  400,   NULL, NULL),
    (31, '{"en": "Beetroot borscht",   "pl": "Barszcz czerwony"}'::jsonb,   'ml', 1,    7,    0.5,  300,   NULL, NULL),
    (32, '{"en": "Coleslaw",           "pl": "Surówka coleslaw"}'::jsonb,   'g',  1,    10,   8,    100,   NULL, NULL),
    (33, '{"en": "Mondongo",           "pl": "Zupa mondongo"}'::jsonb,      'ml', 7,    8,    4,    350,   NULL, NULL),
    (34, '{"en": "Bandeja paisa",      "pl": "Bandeja paisa"}'::jsonb,      'g',  12,   20,   15,   500,   NULL, NULL),
    (35, '{"en": "Pastel de nata",     "pl": "Pastel de nata"}'::jsonb,     'g',  5,    35,   14,   60,    NULL, NULL),
    (36, '{"en": "Cheesecake",         "pl": "Sernik"}'::jsonb,             'g',  7,    25,   18,   120,   NULL, NULL),
    (37, '{"en": "Orange juice",       "pl": "Sok pomarańczowy"}'::jsonb,   'ml', 0.7,  10,   0.2,  NULL,  NULL, NULL),
    (38, '{"en": "Goulash",            "pl": "Gulasz"}'::jsonb,             'g',  15,   6,    10,   350,   NULL, NULL);
